"""add phone to users table2

Revision ID: 019ba4610a85
Revises: 205d01000ff8
Create Date: 2026-09-09 14:32:24.763148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019ba4610a85'
down_revision: Union[str, Sequence[str], None] = '205d01000ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pincode', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pincode')
    op.execute
    # ### end Alembic commands ###
