"""split name into first and last name

Revision ID: 6c51272c011d
Revises: 019ba4610a85
Create Date: 2026-09-10 10:39:09.412836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c51272c011d'
down_revision: Union[str, Sequence[str], None] = '019ba4610a85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:

    
    op.add_column(
        'users',
        sa.Column('first_name', sa.String(length=100), nullable=True)
    )

    op.add_column(
        'users',
        sa.Column('last_name', sa.String(length=100), nullable=True)
    )

    
    op.execute("""
        UPDATE users
        SET
            first_name = split_part(name, ' ', 1),
            last_name = split_part(name, ' ', 2)
    """)

    
    op.alter_column(
        'users',
        'first_name',
        nullable=False
    )

    op.alter_column(
        'users',
        'last_name',
        nullable=False
    )

    
    op.drop_column('users', 'name')




def downgrade() -> None:

    op.add_column(
        'users',
        sa.Column('name', sa.String(length=100), nullable=True)
    )

    op.execute("""
        UPDATE users
        SET name = first_name || ' ' || last_name
    """)

    op.alter_column(
        'users',
        'name',
        nullable=False
    )

    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')



# def upgrade() -> None:
#     """Upgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('first_name', sa.String(length=100), nullable=False))
#     op.add_column('users', sa.Column('last_name', sa.String(length=100), nullable=False))
#     op.drop_column('users', 'name')
#     # ### end Alembic commands ###


# def downgrade() -> None:
#     """Downgrade schema."""
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
#     op.drop_column('users', 'last_name')
#     op.drop_column('users', 'first_name')
#     # ### end Alembic commands ###
